유저 엔티티 생성
sayamae-amateur-baseball-platform/sayamae_be pull request #1
Opened 2023-06-07 13:44 UTC by pooreumu

## 개요(문제 요약)
- 유저 엔티티 클래스 생성 및 일부 필드 테스트 추가

## 작업 사항
- 유저 엔티티 클래스 생성
- 유저 엔티티의 일부 필드(전화번호) 테스트 추가
- 유저 엔티티 검증을 위한 패키지 추가
- nest cli를 이용한 Nest.js 프로젝트 생성시 생기는 불필요한 파일 제거

## 참고 사항
- 새로운 패키지가 추가 돼서 nvm use && npm ci 실행 필요

2023-06-08 03:53 UTC, hyeonjun4460 requested changes
감사합니다! 다만 user entity에서 id 필드가 없는 점이 궁금하네요.
아마 도메인 분석할 당시, user 도메인에 들어갈 멤버변수에서 id에 대한 이야기가 누락되어서 그런 것 같은데, 닉네임과 별개로 id 필드도 있는 것이 좋지 않을까요?

2023-06-08 04:20 UTC, pooreumu commented
> 감사합니다! 다만 user entity에서 id 필드가 없는 점이 궁금하네요. 아마 도메인 분석할 당시, user 도메인에 들어갈 멤버변수에서 id에 대한 이야기가 누락되어서 그런 것 같은데, 닉네임과 별개로 id 필드도 있는 것이 좋지 않을까요?

네 id 필드도 있는게 좋을 거 같아요.  
노션에 작성된 내용으로 user entity를 만들면서 나중에 id필드를 db에 저장할 때 auto increament를 사용하는 pk 컬럼으로 사용하게 될 거 같고, 노션에 저희가 작성한 id에 경우 로그인할 때 사용하는 id로 생각이 들어서 일단 nickname이라고 만들었습니다.

원래는 nickname + 비밀번호 조합을 로그인할 때 사용하려고 생각했는데 그 보다 로그인 할때 전화번호 + 비밀번호로 로그인하는 것 어떻게 생각하시나요?

2023-06-08 07:04 UTC, hyeonjun4460 reviewed
핸드폰을 로그인 시 ID로 쓰는 건 보안적으로 꺼림직할 것 같습니다!
userName이라는 필드를 추가해서 로그인 시 ID로 활용하면 어떨까요?

2023-06-08 08:26 UTC, pooreumu commented
> 핸드폰을 로그인 시 ID로 쓰는 건 보안적으로 꺼림직할 것 같습니다! userName이라는 필드를 추가해서 로그인 시 ID로 활용하면 어떨까요?

네 좋아요

2023-06-08 14:54 UTC, pooreumu commented
user entity에 필드명은 hopePosition이지만 라인업에서 사용되는 실제 배정된 포지션도 똑같은 Position타입일 것으로 예상 돼 hopePosition이 아닌 Position으로 타입명 지었어요

2023-06-09 02:42 UTC, hyeonjun4460 approved these changes
개발을 진행하면서 바뀔 수도 있지만, 포지션 관련된 변수는
1) 희망 포지션
2) 팀에서의 주 포지션
으로 분석되어있죠!

추후에 다시 position -> hopePosition으로 바뀔 수도 있다는 것만 염두에 두면 좋을 것 같습니다.

감사합니다!

2023-06-09 02:42 UTC, merged

2023-06-09 02:45 UTC, pooreumu commented
> 개발을 진행하면서 바뀔 수도 있지만, 포지션 관련된 변수는
> 
> 1) 희망 포지션
> 
> 2) 팀에서의 주 포지션
> 
> 으로 분석되어있죠!
> 
> 
> 
> 추후에 다시 position -> hopePosition으로 바뀔 수도 있다는 것만 염두에 두면 좋을 것 같습니다.
> 
> 
> 
> 감사합니다!


희망 포지션과, 팀에서의 주 포지션이 타입이 다를경우가 있나요? 주 포지션에 있는 포지션중에 희망 할 수 없는 포지션이 있다거나 또는 반대의 경우가 있을 수도 있나요?

2023-06-09 02:47 UTC, hyeonjun4460 commented
> 희망 포지션과, 팀에서의 주 포지션이 타입이 다를경우가 있나요? 주 포지션에 있는 포지션중에 희망 할 수 없는 포지션이 있다거나 또는 반대의 경우가 있을 수도 있나요?

타입이 다를 경우는 없습니다.
희망 포지션에 있는 10개 value가 전부입니다!